name: build mac os
on: [push]
jobs:
  build:
    name: Build MacOS
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .

      - name: build
        run: cmake --build . --clean-first

      - name: run tests
        run: ctest . --extra-verbose

      - uses: actions/upload-artifact@v4
        with:
          name: Nimble Seer MacOS Library
          path: |
            src/lib/libseer.a
